---
caefeeder:
  usePercent: false
  warning: 2500
  critical: 10000

contentfeeder:
  usePercent: false
  warning: 2500
  critical: 10000

blob-cache:
  usePercent: true
  warning: 95
  critical: 98

uapi-cache:
  usePercent: true
  warning: 95
  critical: 98

heap-memory:
  usePercent: true
  warning: 95
  critical: 98

perm-memory:
  usePercent: true
  warning: 99
  critical: 100

license:
  warning: 50
  critical: 20
