Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.define "monitoring_springer" do |monitoring_config|
    monitoring_config.vm.network "private_network", :ip => "192.168.252.103"
  end

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

end
