#!/bin/bash

# set -e
set -x

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

# ----------------------------------------------------------------------------------------

# Parse parameters
while [ $# -gt 0 ]
do
  case "${1}" in
    -H|--host) shift
      HOST="${1}"       ;;
  esac
shift
done

[ -z $WRTA ] && WRTA=100
[ -z $CRTA ] && CRTA=200
[ -z $WPL ] && WPL=5
[ -z $CPL ] && CPL=2

PING_RESPONSE=$( (fping --ipv4 --count=1 --elapsed --unreach --name --stats "$HOST") 2>&1)
ALIVE=$(echo -e "${PING_RESPONSE}" | grep "alive" | awk '{print $1}')
UNREACHABLE=$(echo -e "${PING_RESPONSE}" | grep "unreachable" | awk '{print $1}')
RTA_MIN=$(echo -e "${PING_RESPONSE}" | grep "min round trip time" | awk '{print $1}')
RTA_AVG=$(echo -e "${PING_RESPONSE}" | grep "avg round trip time" | awk '{print $1}')
RTA_MAX=$(echo -e "${PING_RESPONSE}" | grep "max round trip time" | awk '{print $1}')


if [ ${ALIVE} -eq 1 ]
then
  echo "PING OK - Packet loss = 0%, RTA = ${RTA_AVG} ms | rta_min=${RTA_MIN} rta_avg=${RTA_AVG} rta_max=${RTA_MAX}"
  exit ${STATE_OK}
fi

if [ ${UNREACHABLE} -eq 1 ]
then
  echo "PING CRITICAL - Host unreachable"
  exit ${STATE_CRITICAL}
fi

#echo $ALIVE

#| \
#while read -r PING_RESPONSE
#do

  echo ${PING_RESPONSE}


#    regex="([0-9a-fA-F.:]+) +: \[(.*)\], (.*) bytes, (.*) ms \((.*) avg, (.*)% loss\)"
#    [[ $PING_RESPONSE =~ $regex ]]
#    IP="${BASH_REMATCH[1]}"
#    SIZE="${BASH_REMATCH[3]}"
#    ROUNDTRIP="${BASH_REMATCH[4]}"

    NOW=$(date --iso-8601=ns)
#
#     jq \
#         --null-input \
#         --compact-output --ascii-output --monochrome-output \
#         --arg ip "$IP" \
#         --arg size "$SIZE" \
#         --arg roundtrip "$ROUNDTRIP" \
#         --arg now "$NOW" \
#         '{ "ip": $ip, "size": $size|tonumber, "roundtrip": $roundtrip|tonumber, "time": $now }'

#done


exit 1




COUNT=2
TIMEOUT=2
IFS_CURRENT=$IFS
IFS_NL='
'

IFS=$IFS_NL
for ROW in $(/usr/sbin/fping --ipv4 --count=1 --elapsed --unreach --name $HOST) ; do
  PL=$(echo $ROW | awk '{print $5}' | awk 'BEGIN { FS = "%"} { print $1}')
  RTA=$(echo $ROW | awk 'BEGIN { FS = "," } { print $3 }')
#  case "$ROW" in
#    *packet\ loss*)
#      PL=$(echo $ROW | awk '{print $5}' | awk 'BEGIN { FS = "%"} { print $1}')
#      ;;
#    *round-trip*)
#      RTA=$(echo $ROW | awk 'BEGIN { FS = "/" } { print $5 }')
#      ;;
#    *)
#      ;;
#  esac
done

IFS=$IFS_CURRENT

echo $PL
echo $RTA


echo -n "PING "
  if [ "$(echo "$PL > $CPL" | bc)" == "1" ] ; then
    echo -n "CRITICAL"
    EXIT=2
  elif [ "$(echo "$PL > $WPL" | bc)" == "1" ] ; then
    echo -n "WARNING"
    EXIT=1
  elif [ $RTA ] ; then
      if [ "`echo "$RTA > $CRTA" | bc`" == "1" ] ; then
        echo -n "CRITICAL"
        EXIT=2
      elif [ "`echo "$RTA > $WRTA" | bc`" == "1" ] ; then
        echo -n "WARNING"
        EXIT=1
      else
        echo -n "OK"
        EXIT=0
      fi
  else
    echo -n "KO"
    EXIT=2
  fi
echo -n " from $INTERFACE (src $SOURCE, dst $DESTINATION) - Packet loss = $PL%"
  [ $RTA ] && echo -n ", RTA = $RTA ms" || RTA=$CRTA
echo " | 'rta'="$RTA"ms;$WRTA;$CRTA;0 'pl'=$PL%;$WPL;$CPL;0"

exit $EXIT



#/usr/sbin/fping --ipv4 --count=1 --elapsed --unreach --name "${HOST}"

[ $? -eq 0 ] && exit ${STATE_OK}
[ $? -gt 0 ] && exit ${STATE_CRITICAL}



