---
jenkins:
  server:
    'https://pc-ci.coremedia.com':
      - 'vsphere-reports'
      - 'seed'
    'https://cm7-ci.coremedia.com':
      - 'seed'
      - 'license-builder-7.5'
      - 'master-14.0/job/build'
      - 'master-14.0/job/tomcat/job/wcs-build'
      - 'master-14.0/job/tomcat/job/wcs-deploy'
      - 'master-14.0/job/websphere/job/wcs-build'
      - 'master-14.0/job/websphere/job/wcs-deploy'
    'https://release-ci.coremedia.com':
      - 'seed'

